# Generated by Django 3.2.9 on 2021-12-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211217_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
